### ISSUE TITLE
Make rules_appimage build with python3.9 without errors

### ISSUE THREAD

**Issue by nicktanqy** [lalten/rules_appimage#192]
When building rules_appimage with python 3.9 I am seeing this error
```
Traceback (most recent call last):
  File "/home/nicholas.tan/.cache/bazel/_bazel_nicholas.tan/f5a44036e0060c280d6ead74d97554db/sandbox/linux-sandbox/1/execroot/av_stack/bazel-out/k8-opt-exec-ST-a5b2042ccf28/bin/external/rules_appimage/appimage/private/tool/tool.runfiles/av_stack/../rules_appimage/appimage/private/tool/cli.py", line 9, in <module>
    from appimage.private.tool.mkappimage import AppDirParams, make_appimage
  File "/home/nicholas.tan/.cache/bazel/_bazel_nicholas.tan/f5a44036e0060c280d6ead74d97554db/sandbox/linux-sandbox/1/execroot/av_stack/bazel-out/k8-opt-exec-ST-a5b2042ccf28/bin/external/rules_appimage/appimage/private/tool/tool.runfiles/rules_appimage/appimage/private/tool/mkappimage.py", line 17, in <module>
    _ManifestDataT = dict[str, list[str | dict[str, str]]]
TypeError: unsupported operand type(s) for |: 'type' and 'types.GenericAlias
```

Can we use Union instead to avoid the operand type errors? See patch below:

```
diff --git a/appimage/private/tool/mkappimage.py b/appimage/private/tool/mkappimage.py
index 89cc6f9..86567f2 100644
--- a/appimage/private/tool/mkappimage.py
+++ b/appimage/private/tool/mkappimage.py
@@ -10,11 +10,11 @@ import shutil
 import subprocess
 import tempfile
 from pathlib import Path
-from typing import Iterable, NamedTuple
+from typing import Iterable, NamedTuple, Union

 from python import runfiles as bazel_runfiles

-_ManifestDataT = dict[str, list[str | dict[str, str]]]
+_ManifestDataT = dict[str, list[Union[str ,dict[str, str]]]]


 def _get_path_or_raise(path: str) -> Path:
```

**Comment by lalten** [comment]
Thanks for reporting! This seems like https://github.com/lalten/rules_appimage/issues/170 which should be fixed already, are you on the latest release?

**Comment by lalten** [comment]
Not sure why the `from future` import wouldn't work for you.
I can have a look tonight or tomorrow, otherwise feel free to send a PR in the meantime.

**Comment by nicktanqy** [comment]
This might explain why. My project is only pulling in runtime deps (https://github.com/lalten/rules_appimage/blob/1d8ea25b52c5e45ddf15b38c1351ec05f80679ef/deps.bzl#L20) L20-28 as we already have the other dependencies in deps.bzl.

This is how we set-up rules_appimage in our repo:
**repo.bzl**
```
def load_rules_appimage_repo():
    """Loads rules_appimage and dependencies"""
    http_archive(
        name = "rules_appimage",
        patch_args = ["-p1"],
        patch_cmds = ["rm -r tests"],
        patches = ["//third_party/rules_appimage:patch"],  # Patch rules_appimage to remove Optional typing
        sha256 = "b3500b1691d8f831bb2403e51dfd7e78009e06d4bae4eaba3ef127c518de051e",
        strip_prefix = "rules_appimage-1.12.0",
        urls = [
            "https://github.com/lalten/rules_appimage/releases/download/v1.12.0/rules_appimage-1.12.0.tar.gz",
        ],
    )
    ARCHS = {"aarch64": "aarch64", "armv7e-m": "armhf", "i386": "i686", "x86_64": "x86_64"}

    RUNTIME_SHAS = {
        "aarch64": "df1dcce6992a23cdf8728e88ed24f71b3c385f6384f3484ff66f45b9c97f00f2",
        "armhf": "dc6a546bd38a2df4cc6b14b0f2bcf925b0452e8a70d05b6027a631d60d26039b",
        "i686": "480017cfe6fa81785954c4ea39e4d06bc3b8fc287a55082ae781069c5d399116",
        "x86_64": "b86ac7572bb0b3ead120b09430a9dbeadde2f76ae54c1e30659cb54992d60ec1",
    }

    # Only pull appimage runtime arch deps as av-stack already provides the other required deps in rules_appimage.bzl
    for arch, runtime_arch in ARCHS.items():
        http_file(
            name = "appimage_runtime_" + arch,
            executable = True,
            sha256 = RUNTIME_SHAS[runtime_arch],
            urls = ["https://github.com/lalten/type2-runtime/releases/download/build-2022-10-03-c5c7b07/runtime-{}".format(runtime_arch)],
        )
```

and in **WORKSPACE**:
```
# START: rules_appimage support

register_toolchains("@rules_appimage//appimage:all")

# END: rules_appimage support
```

**Comment by lalten** [comment]
rules_appimage uses the requirements.txt Python dependencies only for testing and not at build time. So you should be able to get away with your setup. Maybe I should update the Workspace incantation snippet on the releases some day (I haven't actually used the Workspace version myself in a while and obviously you should migrate to Bzlmod at some point ;) )
